Question 2: CRUD Operations in SQL Server

Objective: Basic SQL Server interactions.

In [1]:
import sqlite3
import pandas as pd

In [2]:
connection = sqlite3.connect("metals.db")
cursor = connection.cursor()

Creating an SQL table schema to store time-series metal prices. Including fields like Date, Metal, Price:

In [6]:
cursor.execute("""
CREATE TABLE MetalPrices (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Date DATE NOT NULL,
    Metal VARCHAR(50) NOT NULL,
    Price DECIMAL(18,4) NOT NULL
)
""")

In [7]:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

Empty DataFrame
Columns: [Id, Date, Metal, Price]
Index: []

Demonstrating basic CRUD operations:

In [ ]:
Create:

In [8]:
cursor.execute("""
INSERT INTO MetalPrices (Date, Metal, Price)
VALUES 
('2010-01-01', 'Copper', 7375),
('2010-01-01', 'Aluminum', 2200),
('2010-01-01', 'Zinc', 2500),
('2010-01-01', 'Lead', 2100),
('2010-01-01', 'Nickel', 15000);
""")

In [9]:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

   Id        Date     Metal  Price
0   1  2010-01-01    Copper   7375
1   2  2010-01-01  Aluminum   2200
2   3  2010-01-01      Zinc   2500
3   4  2010-01-01      Lead   2100
4   5  2010-01-01    Nickel  15000

Read:

In [10]:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

   Id        Date     Metal  Price
0   1  2010-01-01    Copper   7375
1   2  2010-01-01  Aluminum   2200
2   3  2010-01-01      Zinc   2500
3   4  2010-01-01      Lead   2100
4   5  2010-01-01    Nickel  15000

Update:

In [12]:
cursor.execute("""
UPDATE MetalPrices
SET Price = 7400
WHERE Metal = 'Copper' AND Date = '2010-01-01';
""")

In [13]:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

   Id        Date     Metal  Price
0   1  2010-01-01    Copper   7400
1   2  2010-01-01  Aluminum   2200
2   3  2010-01-01      Zinc   2500
3   4  2010-01-01      Lead   2100
4   5  2010-01-01    Nickel  15000

Delete:

In [15]:
cursor.execute("""
DELETE FROM MetalPrices
WHERE Metal = 'Aluminum' AND Date = '2010-01-01';
""")

In [16]:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

   Id        Date   Metal  Price
0   1  2010-01-01  Copper   7400
1   3  2010-01-01    Zinc   2500
2   4  2010-01-01    Lead   2100
3   5  2010-01-01  Nickel  15000