Question 2: CRUD Operations in SQL Server

Objective: Basic SQL Server interactions.

In [1]:
# Importing sqlite3 to interact with database, and pandas for data manipulation:
import sqlite3
import pandas as pd

Establishing connection and setting up through the cursor variable which will be used to interact with database in this task:

In [2]:
connection = sqlite3.connect("metals.db")
cursor = connection.cursor()

Creating an SQL table schema to store time-series metal prices. Including fields like Date, Metal, Price:

A Table is created called MetalPrices. The Integrity Constraints of this Table are the Id, which is the primary key and will automatically increment so that it is not a required field for every insertion operation and the like. The Date column is of Date data type to hold the time attribute of this time-series. While the Metal and Price columns are of string to hold the Metal's name and that Metal's corresponding settlement price of that particular day respectively. Date, Metal and Price fields are Not Null, and hence, required, as these are the elements of the data-set that we want to store in this database.

In [6]:
# Creation of Table occurs in the Database:
cursor.execute("""
CREATE TABLE MetalPrices (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Date DATE NOT NULL,
    Metal VARCHAR(50) NOT NULL,
    Price DECIMAL(18,4) NOT NULL
)
""")

To verify that the Table has been created and that it does not contain any data points at this stage:

Please Note: Retrieval is done throughout this Notebook using read_sql() in order to retrieve data from the table and then load it into a DataFrame so that it can be displayed in a tabular format in the Notebook, to enhance readability and maintainability.

In [7]:
# Retrieval query to attempt accessing the above created Table:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

Empty DataFrame
Columns: [Id, Date, Metal, Price]
Index: []

Therefore, since the result shows the Column Headers as specified with no data points inside this DataFrame at this point of time, it is hence, verified that the table Metalprices has been created and now exists in the database with no current data points in it so far.

Demonstrating basic CRUD operations:

In [ ]:
Create:

Making Insertions with data which is made only for the purposes of this demonstration and not sourced from anywhere specific, into the MetalPrices Table:

In [8]:
# Making 5 data points within the Insertion query:
cursor.execute("""
INSERT INTO MetalPrices (Date, Metal, Price)
VALUES 
('2010-01-01', 'Copper', 7375),
('2010-01-01', 'Aluminum', 2200),
('2010-01-01', 'Zinc', 2500),
('2010-01-01', 'Lead', 2100),
('2010-01-01', 'Nickel', 15000);
""")

To verify that the above Insertions have taken place, I retrieve the values from the MetalPrices Table:

In [9]:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

   Id        Date     Metal  Price
0   1  2010-01-01    Copper   7375
1   2  2010-01-01  Aluminum   2200
2   3  2010-01-01      Zinc   2500
3   4  2010-01-01      Lead   2100
4   5  2010-01-01    Nickel  15000

Hence, the Insertions of the values for this demonstration have taken place.

Read:

In [10]:
# Retrieving all the data points, using "*" from the MetalPrices Table:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

   Id        Date     Metal  Price
0   1  2010-01-01    Copper   7375
1   2  2010-01-01  Aluminum   2200
2   3  2010-01-01      Zinc   2500
3   4  2010-01-01      Lead   2100
4   5  2010-01-01    Nickel  15000

Therefore, the Retrieval of all the data points has taken place, as the DataFrame df here demonstrates.

Update:

Making an Update query to modify the Price of Copper on the 1st of January, 2010 to 7400:

In [12]:
# Updating the data point at the locations through the filter of the specified Metal and Date using the "WHERE" clause, 
# and "SET" to specify the value I want it modified to for this demonstration:
cursor.execute("""
UPDATE MetalPrices
SET Price = 7400
WHERE Metal = 'Copper' AND Date = '2010-01-01';
""")

To verify that the above Update has taken place, I retrieve the values from the MetalPrices Table:

In [13]:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

   Id        Date     Metal  Price
0   1  2010-01-01    Copper   7400
1   2  2010-01-01  Aluminum   2200
2   3  2010-01-01      Zinc   2500
3   4  2010-01-01      Lead   2100
4   5  2010-01-01    Nickel  15000

Hence, the Update of the value has taken place, as reflected in the above DataFrame df.

Delete:

Making Deletion in the MetalPrices Table:

In [15]:
# Deleting the data point at the locations that I want to delete for this demonstration through the filter of the 
# specified Metal and Date using the "WHERE" clause:
cursor.execute("""
DELETE FROM MetalPrices
WHERE Metal = 'Aluminum' AND Date = '2010-01-01';
""")

To verify that the above Delete has taken place, I retrieve the values from the MetalPrices Table:

In [16]:
df = pd.read_sql("SELECT * FROM MetalPrices", connection)
df

   Id        Date   Metal  Price
0   1  2010-01-01  Copper   7400
1   3  2010-01-01    Zinc   2500
2   4  2010-01-01    Lead   2100
3   5  2010-01-01  Nickel  15000

Hence, the Deletion of the value has taken place, as reflected in the above DataFrame df.

In order to be sure that the effects of the above operations of the database are permanently saved to the database, the following commit() is called:

In [ ]:
# To permanently save the changes made to the database, the commit() is called:
connection.commit()

After running all the cells in this Notebook, if the database named metals is accessed through any other Notebook, all the changes made to the database from this Notebook here will also now reflect. Calling commit() above assures so.